### ISSUE TITLE
Youtu.be links don't work on the web app.

### ISSUE THREAD

**Issue by BalintXHD** [deepjyoti30/ytmdl-web-v2#66]
Just as the title says, it loads it. It even lets me select the metadata, but it doesn't have a download link.

**Comment by Xishalet** [comment]
Also having this problem

**Comment by deepjyoti30** [comment]
Thanks for reporting, just tried to reproduce and indeed the issue is present. Will let you guys know once it is fixed!

**Comment by deepjyoti30** [comment]
@Xishalet @BalintXHD The issue is now fixed and fix is live. You guys head over to the website and try it out. I already tested the fix and it's working nicely.

BTW, make sure to force refresh the page since the cache usually doesn't refresh right away. Force refresh can be done using `ctrl+shift+r`

**Comment by otterfree** [comment]
I've tried, it's still not working. refreshing only sends me back to the home page rather than giving me a download link.

**Comment by deepjyoti30** [comment]
@otterfree Can you try now. This seems like related to the other issue that you reported which is #70 which is now fixed.

**Comment by BalintXHD** [comment]
Sorry for ghosting this, but it finally works. Thanks!

**Comment by otterfree** [comment]
thank you! just tried and it's working again. i'm really happy i can use this app again ^v^
